### ISSUE TITLE
World Community Grid Stats Don't Post

### ISSUE THREAD

**Issue by AzEkologi** [AustinConlon/BOINC-iOS-watchOS#26]
My stats for World Community Grid post as zero.  When setting up WCG on the app, the interface only asks for user name, not password.  Your original reply was that "World Community Grid does not require passwords for getting your account stats. Unless I’m mistaken, they also moved from usernames to emails".  I don't believe that this is correct as, when I log into the account via their website, I log in with my username (email), and a password (different from my email).

**Comment by AustinConlon** [comment]
Sorry for the late response. I had another of the same report, and after I responded they said "It turns out public stats are disabled by IBM you need to toggle them on in your account and in my case using my email not my username then worked." 

In the past I was able to display stats from only a username and not a password, but it sounds like IBM making public stats opt-in broke that functionality. Hopefully I can still support World Community Grid, I'll look into this and get back to you.

**Comment by AustinConlon** [comment]
Hi, can you go to the World Community Grid settings page for "Data Sharing" (https://www.worldcommunitygrid.org/ms/viewDataSharing.action), make sure that "Display my data" is selected, and then check the app to see if it works? Note that the page also says "In order to make your data privacy settings public, you must have a verified email address and have created a username." The username is how you add it to my app. Sorry about that, and let me know if it works. I'll add this information in the app in an update shortly. At some point IBM decided to make "Hide my data" the default, which mistakenly shows the credits to be 0 when that setting is on.
